spring:
  application:
    name: cheongForDo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.5

jwt:
  secret: ${JWT_SECRET}
  expire:
    access: 86400000
    refresh: 604800000

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG


