spring:
  application:
    name: cheongForDo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheong?serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expire:
    access: 86400000
    refresh: 604800000

server:
  port: 8080
  address: 10.80.161.247

admin:
  id: minari
  password: minari123!
  email: minari@gmail.com
  authority: ROLE_ADMIN


logging:
  level:
    org:
      springframework:
        web: DEBUG


