spring:
  application:
    name: cheongForDo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheong?serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-4o
          temperature: 0.6

jwt:
  secret: ${JWT_SECRET}
  expire:
    access: 86400000
    refresh: 604800000

server:
  port: 8080

admin:
  id: minari
  password: minari123!
  email: minari@gmail.com
  authority: ROLE_ADMIN


logging:
  level:
    org:
      springframework:
        web: DEBUG


